import waterSrcSetWebP from "@app/imgShared/water/water_3072.jpeg?format=webp&w=200;320;400;768&srcset&imagetools";
import waterSrcFull from "@app/imgShared/water/water_3072.jpeg?w=1280&imagetools";
import waterSrcSetJpeg from "@app/imgShared/water/water_3072.jpeg?w=200;400;768;1280&srcset&imagetools";
import waterSrc from "@app/imgShared/water/water_768.jpeg?w=200&format=webp&imagetools";
import waterMeta from "@app/imgShared/water/water_768.jpeg?w=200&meta=width;height&imagetools";
import { Text } from "@geist-ui/core";

import TextPicture from "@app/components/TextPicture";
import quiberonSrcSetWebP from "@app/imgShared/quiberon.jpeg?format=webp&w=200;320;400;768&srcset&imagetools";
import quiberonSrcFull from "@app/imgShared/quiberon.jpeg?w=1280&imagetools";
import quiberonSrc from "@app/imgShared/quiberon.jpeg?w=200&format=webp&imagetools";
import quiberonMeta from "@app/imgShared/quiberon.jpeg?w=200&meta=width;height&imagetools";
import quiberonSrcSetJpeg from "@app/imgShared/quiberon.jpeg?w=200;400;768;1280&srcset&imagetools";

export default function Water() {
  const sizes =
    "((min-width: 800px) or ((min-resolution: 2dppx) and (min-width: 480px))) 320px, ((min-width: 1024px) and (min-resolution: 3dppx)) 480px, 200px";
  return (
    <section>
      <Text h3 mt={2}>
        Water
      </Text>
      <TextPicture
        figure
        caption="This is water."
        square
        image={
          <a href={waterSrcFull} style={{ display: "contents" }}>
            <picture>
              <source
                type="image/webp"
                srcSet={waterSrcSetWebP}
                sizes={sizes}
              />
              <source
                type="image/jpeg"
                srcSet={waterSrcSetJpeg}
                sizes={sizes}
              />
              <img
                src={waterSrc}
                alt="Water"
                loading="lazy"
                width={waterMeta.width}
                height={waterMeta.height}
                sizes={sizes}
              />
            </picture>
          </a>
        }
      >
        This is a water-like picture generated by StableDiffusion. It makes no
        sense.
        <br />I love water and the ocean, but I rarely see oceans since I live
        in <s>an ugly</s> a big city far away from the sea. Cologne has a river
        at least!
      </TextPicture>
      <TextPicture
        orient="left"
        divider
        float
        square
        image={
          <a href={quiberonSrcFull} style={{ display: "contents" }}>
            <picture>
              <source
                type="image/webp"
                srcSet={quiberonSrcSetWebP}
                sizes={sizes}
              />
              <source
                type="image/jpeg"
                srcSet={quiberonSrcSetJpeg}
                sizes={sizes}
              />
              <img
                src={quiberonSrc}
                alt="Moritz in Quiberon, France"
                loading="lazy"
                width={quiberonMeta.width}
                height={quiberonMeta.height}
                sizes={sizes}
              />
            </picture>
          </a>
        }
      >
        This is me walking an actual beach in Quiberon, France. One of those
        rare lucky times in my life when I made it to an actual beach. 🙂
      </TextPicture>
    </section>
  );
}
